TEAM_NAME_MAP = {
    # Mappings from multiple data sources to team abbreviations
    "Angels": "LAA",
    "Athletics": "OAK",
    "Astros": "HOU",
    "Blue Jays": "TOR",
    "Braves": "ATL",
    "Brewers": "MIL",
    "Cardinals": "STL",
    "Cubs": "CHC",
    "Diamondbacks": "ARI",
    "D-backs": "ARI",
    "Dodgers": "LAD",
    "Giants": "SFG",
    "Guardians": "CLE",
    "Mariners": "SEA",
    "Marlins": "MIA",
    "Mets": "NYM",
    "Nationals": "WSN",
    "Orioles": "BAL",
    "Padres": "SDP",
    "Phillies": "PHI",
    "Pirates": "PIT",
    "Rangers": "TEX",
    "Rays": "TBR",
    "Red Sox": "BOS",
    "Reds": "CIN",
    "Rockies": "COL",
    "Royals": "KCR",
    "Tigers": "DET",
    "Twins": "MIN",
    "White Sox": "CHW",
    "Yankees": "NYY",
    "LAA": "LAA",
    "HOU": "HOU",
    "OAK": "OAK",
    "TOR": "TOR",
    "ATL": "ATL",
    "MIL": "MIL",
    "STL": "STL",
    "CHC": "CHC",
    "ARI": "ARI",
    "LAD": "LAD",
    "SFG": "SFG",
    "CLE": "CLE",
    "SEA": "SEA",
    "MIA": "MIA",
    "NYM": "NYM",
    "WSN": "WSN",
    "BAL": "BAL",
    "SDP": "SDP",
    "PHI": "PHI",
    "PIT": "PIT",
    "TEX": "TEX",
    "TBR": "TBR",
    "BOS": "BOS",
    "CIN": "CIN",
    "COL": "COL",
    "KCR": "KCR",
    "DET": "DET",
    "MIN": "MIN",
    "CHW": "CHW",
    "NYY": "NYY"
}
