TEAM_NAME_MAP = {
    "Washington": "WSN",
    "Nationals": "WSN",
    "WSH": "WSN",
    "Washington Nationals": "WSN",
    "Oakland": "ATH",
    "Athletics": "ATH",
    "OAK": "ATH",
    "Tampa Bay": "TBR",
    "Rays": "TBR",
    "Tampa Bay Rays": "TBR",
    "New York Mets": "NYM",
    "Mets": "NYM",
    "NYM": "NYM",
    "Colorado": "COL",
    "Rockies": "COL",
    "COL": "COL",
    "Atlanta": "ATL",
    "Braves": "ATL",
    "Atlanta Braves": "ATL",
    "Pittsburgh": "PIT",
    "Pirates": "PIT",
    "PIT": "PIT",
    "Toronto": "TOR",
    "Blue Jays": "TOR",
    "TOR": "TOR",
    "San Diego": "SDP",
    "Padres": "SDP",
    "SD": "SDP",
    "San Diego Padres": "SDP",
    "Texas": "TEX",
    "Rangers": "TEX",
    "TEX": "TEX",
    "Baltimore": "BAL",
    "Orioles": "BAL",
    "BAL": "BAL",
    "Minnesota": "MIN",
    "Twins": "MIN",
    "MIN": "MIN",
    "St. Louis": "STL",
    "Cardinals": "STL",
    "STL": "STL",
    "Houston": "HOU",
    "Astros": "HOU",
    "HOU": "HOU",
    "Philadelphia": "PHI",
    "Phillies": "PHI",
    "PHI": "PHI",
    "Los Angeles Angels": "LAA",
    "Angels": "LAA",
    "LAA": "LAA",
    "Chicago White Sox": "CHW",
    "White Sox": "CHW",
    "CHW": "CHW",
    "Miami": "MIA",
    "Marlins": "MIA",
    "MIA": "MIA",
    "Seattle": "SEA",
    "Mariners": "SEA",
    "SEA": "SEA",
    "Boston": "BOS",
    "Red Sox": "BOS",
    "BOS": "BOS",
    "Chicago White Sox": "CHW",
    "Philadelphia Phillies": "PHI",
    "Houston Astros": "HOU",
    "Atlanta Braves": "ATL",
    "Miami Marlins": "MIA",
    "Seattle Mariners": "SEA",
    "St. Louis Cardinals": "STL",
    "Boston Red Sox": "BOS",
    "Minnesota Twins": "MIN",
    "Texas Rangers": "TEX",
    "Toronto Blue Jays": "TOR",
    "Pittsburgh Pirates": "PIT",
    "Colorado Rockies": "COL",
    "New York Mets": "NYM",
    "Oakland Athletics": "ATH",
    "Arizona": "ARI",
    "Diamondbacks": "ARI",
    "ARI": "ARI",
    "New York Yankees": "NYY",
    "Yankees": "NYY",
    "NYY": "NYY",
    "Cincinnati": "CIN",
    "Reds": "CIN",
    "CIN": "CIN",
    "Milwaukee": "MIL",
    "Brewers": "MIL",
    "MIL": "MIL"
}
