TEAM_NAME_MAP = {
    # Mappings from multiple data sources to team abbreviations
    "Angels": "LAA",
    "Athletics": "ATH",
    "Astros": "HOU",
    "Blue Jays": "TOR",
    "Braves": "ATL",
    "Brewers": "MIL",
    "Cardinals": "STL",
    "Cubs": "CHC",
    "Diamondbacks": "ARI",
    "D-backs": "ARI",
    "Dodgers": "LAD",
    "Giants": "SFG",
    "Guardians": "CLE",
    "Mariners": "SEA",
    "Marlins": "MIA",
    "Mets": "NYM",
    "Nationals": "WSN",
    "Orioles": "BAL",
    "Padres": "SDP",
    "Phillies": "PHI",
    "Pirates": "PIT",
    "Rangers": "TEX",
    "Rays": "TBR",
    "Red Sox": "BOS",
    "Reds": "CIN",
    "Rockies": "COL",
    "Royals": "KCR",
    "Tigers": "DET",
    "Twins": "MIN",
    "White Sox": "CHW",
    "Yankees": "NYY",
    "LAA": "LAA",
    "HOU": "HOU",
    "OAK": "ATH",
    "TOR": "TOR",
    "ATL": "ATL",
    "MIL": "MIL",
    "STL": "STL",
    "CHC": "CHC",
    "ARI": "ARI",
    "LAD": "LAD",
    "SFG": "SFG",
    "CLE": "CLE",
    "SEA": "SEA",
    "MIA": "MIA",
    "NYM": "NYM",
    "WSN": "WSN",
    "BAL": "BAL",
    "SDP": "SDP",
    "PHI": "PHI",
    "PIT": "PIT",
    "TEX": "TEX",
    "TBR": "TBR",
    "BOS": "BOS",
    "CIN": "CIN",
    "COL": "COL",
    "KCR": "KCR",
    "DET": "DET",
    "MIN": "MIN",
    "CHW": "CHW",
    "NYY": "NYY",
    "Los Angeles Angels": "LAA",
    "Oakland Athletics": "ATH",
    "Houston Astros": "HOU",
    "Toronto Blue Jays": "TOR",
    "Atlanta Braves": "ATL",
    "Milwaukee Brewers": "MIL",
    "St. Louis Cardinals": "STL",
    "St Louis Cardinals": "STL",
    "Chicago Cubs": "CHC",
    "Arizona Diamondbacks": "ARI",
    "Los Angeles Dodgers": "LAD",
    "San Francisco Giants": "SFG",
    "Cleveland Guardians": "CLE",
    "Seattle Mariners": "SEA",
    "Miami Marlins": "MIA",
    "New York Mets": "NYM",
    "Washington Nationals": "WSN",
    "Baltimore Orioles": "BAL",
    "San Diego Padres": "SDP",
    "Philadelphia Phillies": "PHI",
    "Pittsburgh Pirates": "PIT",
    "Texas Rangers": "TEX",
    "Tampa Bay Rays": "TBR",
    "Boston Red Sox": "BOS",
    "Cincinnati Reds": "CIN",
    "Colorado Rockies": "COL",
    "Kansas City Royals": "KCR",
    "Detroit Tigers": "DET",
    "Minnesota Twins": "MIN",
    "Chicago White Sox": "CHW",
    "New York Yankees": "NYY",
    "SD": "SDP",
    "SF": "SFG",
    "KC": "KCR",
    "TB": "TBR",
    "NY Yankees": "NYY",
    "St. Louis": "STL",
    "Arizona": "ARI",
    "Chi Cubs": "CHC",
    "SF Giants": "SFG",
    "LA Dodgers": "LAD",
    "Philadelphia": "PHI",
    "Boston": "BOS",
    "Detroit": "DET",
    "Baltimore": "BAL",
    "San Diego": "SDP",
    "Kansas City": "KCR",
    "LA Angels": "LAA",
    "NY Mets": "NYM",
    "Cleveland": "CLE",
    "Toronto": "TOR",
    "Chi Sox": "CHW",
    "Tampa Bay": "TBR",
    "Sacramento": "ATH",
    "Miami": "MIA",
    "Washington": "WSN",
    "Milwaukee": "MIL",
    "Seattle": "SEA",
    "Cincinnati": "CIN",
    "Minnesota": "MIN",
    "Atlanta": "ATL",
    "Pittsburgh": "PIT",
    "Texas": "TEX",
    "Houston": "HOU",
    "Colorado": "COL",
    "WAS": "WSN"
}
